### ISSUE TITLE
Define Process/Task User Stories

### ISSUE THREAD

**Issue by ivanminutillo** [django-rea/rea-app#11]
As we have decided process/task will be the first part of REA-app implemented, it would be great to define togheter the user stories that we want to include in this epic.

**Comment by fosterlynn** [comment]
Here is an attempt at defining the user stories currently involved in process/task side.  I may have missed some, will continue to poke around.  And this isn't meant to imply we need to do all of them.

This does not include the following.  I can add if needed.
* creating recipes
* planning using recipes
* inventory view and management

Note: There are some things we should eventually verify, see "?".  I think maybe some of the requirements for coordinator vs member should be reviewed.

Note also anything a member can do, a coordinator can do. 
#### Project
* As a person, I want to see all the projects I’m subscribed to, by my role.
* As a person, I want to see all the projects I am allowed to subscribe to, but am not yet subscribed.
* As a person, I want to create a new project.
* As a member of a project, I want to invite other agents to the project. (does this exist?)
* As a member of a project, I want to see all the details of the project.
* As a coordinator of a project (?), I want to edit the details of the project, including project associations.
* As a member of a project, I want to see the contribution history related to the project, filtered by date and member.
#### Work, planning, coordinating
* As a person, I want to see my contribution history, filtered by date, event type, paid/unpaid.
* As a person, I can add and remove the skills on my skill profile.
* As a member, I want to see all the tasks of any type (process, simple, extra) I am working on.
* As a member, I want to see all the open tasks (process, simple) that I could work on based on my skills.
##### Simple tasks
* As a member of a project, I want to create new simple tasks for me or someone else to work on.
* As a member, I can decline a simple task someone has assigned to me.
* As a member, I can change any simple task that I have created.
* As a member, I can delete any simple task that I have created, if work has not been done on it.
* As a member, I can record my work on a simple task and mark it complete.
##### Processes
* As a member of a project, I want to plan a process from scratch.
* As a member of a project, I want to be able to change details of the process.
* As a coordinator of a project (?), I want to be able to delete a process that has no actual events recorded on it.
* As a member of a project, I want to be able to add requirements of any type in the planned process.
* As a member of a project, I can change a non-work requirement in the planned process.
* As a member of a project, I can delete a non-work requirement of any type in the planned process, if there are no actual events logged against it.
* As a coordinator of a project, I can change a work requirement in the planned process.
* As a coordinator of a project, I can delete a work requirement of any type in the planned process, if there are no actual events logged against it.
* As a member of a project, I can commit to working on a process task.
* As a member of a project, I can remove my commitment to work on a process task.
* As a member of a project, I can record my work on a planned process task.
* As a member of a project, I can record my work for a process without a planned process task.
* As a member of a project, I can change my recorded work on a process.
* As a member of a project, I can delete my recorded work on a process.
* As a member of a project, I can join a process task that someone else already committed to, notifying the other person.
* As a member of a project, I can invite others to help me with a process task that I already committed to, notifying everyone with that skill.
* As a member of a project, I can record non-work inputs and outputs (materials, equipment usage, citations, output produced) that have been planned.
* As a member of a project, I can record non-work inputs and outputs (materials, equipment usage, citations, output produced) that have not been planned.
* As a member of a project, I can delete non-work inputs and outputs (materials, equipment usage, citations, output produced) that I have created.
* As a member of a project, I can see previous and next processes to the one I am working on, so that I can understand the needs for my outputs and the status of my inputs in the sequence of processes.
* As a member of a project, I can mark a process finished.
* As a member of a project, I can mark a finished process as unfinished.
##### Extra tasks
* As a member of a project, I want to log non-process-related unplanned work (extra tasks).
* As a member of a project, I can change non-process-related unplanned work (extra tasks) that I created.
* As a member of a project, I can delete non-process-related unplanned work (extra tasks) that I created.
#### Orders
* As a member, I want to see all the open work orders and customer orders (?) for projects I am associated with.
* As a member, I want to see all the deliverables and processes for each deliverable for an open work order or customer order (?) for projects I am associated with.
* As a coordinator (?), I want to be able to add a deliverable to a work order. (and customer order?)
* As a coordinator (?), I want to be able to reschedule a deliverable forward, changing all the involved processes.
* As a coordinator (?), I want to be able to add a process into a workflow sequence for a planned deliverable.

**Comment by ivanminutillo** [comment]
Awesome :-) 
I'd like as first step, to reduce this list as much as we can in order to have an MVP version of it, in order to start making the first basic working prototype (the choosed user stories could be our first epic?) .
This epic should implement the minimum number of user stories we think are needed to define the backbone of process/task section.
I've started to edit @fosterlynn list, if you think it could be a good approach feel free to improve it ( adding / editing / removing stories) as I think the following list is still far for a good backbone  :)

**Project**

- As a person, I want to see all the projects I am allowed to subscribe to
- As a person, I want to create a new project.
- As a member of a project, I want to see all the details of the project.
- As a coordinator of a project (?), I want to edit the details of the project, including project associations.
- As a member of a project, I want to see the contribution history related to the project.

**Work, planning, coordinating**

- As a person, I want to see all the projects I’m subscribed to, by my role.
- As a person, I want to see my contribution history
- As a person, I can add and remove the skills on my skill profile.
- As a member, I want to see all the tasks of any type (process, simple, extra) I am working on.

**Simple tasks**

- As a member of a project, I want to create new simple tasks.
- As a member, I can edit any simple task that I have created.
- As a member, I can delete any simple task that I have created, if work has not been done on it.
- As a member, I can record my work on a simple task and mark it complete.

**Processes**

- As a member of a project, I want to plan a process from scratch.
- As a member of a project, I want to be able to edit details of the process.
- As a coordinator of a project (?), I want to be able to delete a process that has no actual events recorded on it.
- As a member of a project, I can commit to working on a process task.
- As a member of a project, I can remove my commitment to work on a process task.
- As a member of a project, I can record my work on a planned process task.
- As a member of a project, I can edit my recorded work on a process.
- As a member of a project, I can delete my recorded work on a process.
- As a member of a project, I can record non-work inputs and outputs (materials, equipment usage, citations, output produced) that have been planned.
- As a member of a project, I can mark a process finished.
- As a member of a project, I can mark a finished process as unfinished.

**Orders**

- As a member, I want to see all the open work orders and customer orders (?) for projects I am associated with.
- As a member, I want to see all the deliverables and processes for each deliverable for an open work order or customer order (?) for projects I am associated with.
- As a coordinator (?), I want to be able to add a deliverable to a work order. (and customer order?)
- As a coordinator (?), I want to be able to reschedule a deliverable forward, changing all the involved processes.
- As a coordinator (?), I want to be able to add a process into a workflow sequence for a planned deliverable.

**Comment by fosterlynn** [comment]
I'll shorten it more.  It looks like you got rid of all the non-work inputs and outputs except the create, so I'll get rid of that all together.  That eliminates the connection of processes to each other, which is kind of the heart of the model, but all in good time.  :)  But I think that allows elimination of the order pieces.  I think this will correspond with where the initial process users in Freedom Coop will be starting out, which is just recording work and being able to see it in lists.

I got rid of project level creation and editing, that can happen in the main app for now, it is infrequent.   Also took off remaining membership functionality.  OK with everyone?

I changed a permission so that members can do everything, so now there is no "coordinator only" user story.  I think that is fine for process/task stuff, based on telegram discussions.

What do you all think, for starters?

**Project**

- As a person, I want to see all the projects I am allowed to subscribe to.
- As a member of a project, I want to see all the details of the project.
- As a member of a project, I want to see the contribution history related to the project.
- As a member, I can edit any work contributions I have made. [edit]
- As a member, I can delete any work contributions I have made. [edit]

**Work, planning, coordinating**

- As a person, I want to see all the projects I’m subscribed to, by my role.
- As a person, I want to see my contribution history.
- As a person, I can add and remove the skills on my skill profile.
- As a member, I want to see all the tasks of any type (process, simple for now - extra later) I am working on.

**Simple tasks**

- As a member of a project, I want to create new simple tasks.
- As a member, I can edit any simple task that I have created.
- As a member, I can delete any simple task that I have created, if work has not been done on it.
- As a member, I can record my work on a simple task and mark it complete.

**Processes**

- As a member of a project, I want to plan a process from scratch (only need work events for now).
- As a member of a project, I want to be able to edit details of the process.
- As a member of a project, I want to be able to delete a process that has no actual events recorded on it.
- As a member of a project, I want to be able to add work requirements to the planned process. [edit]
- As a member of a project, I can change a work requirement in the planned process that I created. [edit]
- As a member of a project, I can delete a work requirement of any type in the planned process that I created, if there are no actual events logged against it. [edit]
- As a member of a project, I can commit to working on a process task.
- As a member of a project, I can remove my commitment to work on a process task.
- As a member of a project, I can record my work on a planned process task.
- As a member of a project, I can edit my recorded work on a process. [edit: we can remove this if we want for now, since it is added above]
- As a member of a project, I can delete my recorded work on a process.  [edit: we can remove this if we want for now, since it is added above]
- As a member of a project, I can mark a process finished.
- As a member of a project, I can mark a finished process as unfinished.

**Comment by fosterlynn** [comment]
If it fits in, we could add back in the work coordination features of process logging, that would be some level of completion of the work pieces.

Also I notice that we probably will need the ability to create requirements on a process after it is initially created from scratch, just for work.  I'll add that back in as an edit.

**Comment by ivanminutillo** [comment]
I didn't thougth that getting rid of non-work inputs and outputs would eliminate the correlations between processes, if that's a core value of processes/task maybe we should reintegrate them in the flow...don't you think?

**Comment by fosterlynn** [comment]
OK, one more - people will need to be able to edit their simple task contributions also.  I think I'll add it to the contribution report, so that will cover editing of process task contributions too.  So we can take it out of process logging, if we want to get to "minimal".

>I didn't thougth that getting rid of non-work inputs and outputs would eliminate the correlations between processes, if that's a core value of processes/task maybe we should reintegrate them in the flow...don't you think?

Well it is the resources created, and then consumed or used or cited, that create the process chains.  They are loosely coupled through resource flows, not directly connected.  It is true that that data structure may eventually drive the UI in some ways, so maybe we want to think about it.  But it is also true that we could live without it if people want to start just with logging work, and not working with the value flows.  For example, just logging work with nothing else logged would allow a minimally functional distribution of income, just not based on deliverables or traveling back through the value chain.

**Comment by bhaugen** [comment]
See also https://github.com/FreedomCoop/valuenetwork/wiki/Loose-coupling-vs-tight-coupling,-or,-direct-process-dependencies-vs-resource-flows

**Comment by fosterlynn** [comment]
>Well it is the resources created, and then consumed or used or cited, that create the process chains. They are loosely coupled through resource flows, not directly connected. It is true that that data structure may eventually drive the UI in some ways, so maybe we want to think about it. But it is also true that we could live without it if people want to start just with logging work, and not working with the value flows.

Note, I'm not expressing an opinion.  I think the users of the software need to generally prioritize things.  I also don't know the technology you are using, so I don't know how minimal a MVP needs to be to get something out there.  And I don't know if it will be hard or easy to morph this much simpler suggestion into something with a value flow type of interface.  From the discussion we have had, maybe it could be added on top of this? 

What I have heard of FC requirements from say the artists collective, is they just want to log work with multiple participants (therefore process logging) and want to divide up the income based on contributions, by month - so they don't need flows.  Decentrale could possibly get by without process flows?  The FC nodes maybe can too, not sure?  Ale/Guy doing translation.... they might benefit from connecting processes, but they can use the regular app too. Those are the immediate users I know about, although there may be more.  In general, it is perhaps not an intuitive concept, so unless people come from a supply chain or serious manufacturing background, they don't tend to immediately say "hey, that will be great  for us" when they first see it.

If this is used by Sensorica or any of the Sensorica spin-offs (Matrioshka, etc.), they will need the full process flows implemented.  But they aren't here helping yet.

Me personally, I can get much more excited by implementing the full model, but I also think we need to respond to actual needs as quickly as we can, which so far we have not been good about. In other words, I abstain from the MVP decision and will continue to provide input as best I can. :blush:

**Comment by ivanminutillo** [comment]
> Well it is the resources created, and then consumed or used or cited, that create the process chains. They are loosely coupled through resource flows, not directly connected. It is true that that data structure may eventually drive the UI in some ways, so maybe we want to think about it.

yes, you're right, I didn't understand that becouse I am still get used to think as conventional project with management systems with direct dependencies instead of the possibility to have indirect links between processes (loose coupling)... argh it's hard to break abitudinary thinking model 🔨 
that said I think they are part of the **core** of this section, becouse they have to drive the UI, in order to accustom users to change their way of thinking more easily imho. 
So I've tried to re-insert in our epic...here the update version:

**Project**

- As a person, I want to see all the projects I am allowed to subscribe to.
- As a member of a project, I want to see all the details of the project.
- As a member of a project, I want to see the contribution history related to the project.
- As a member, I can edit any work contributions I have made. [edit]
- As a member, I can delete any work contributions I have made. [edit]

**Work, planning, coordinating**

- As a person, I want to see all the projects I’m subscribed to, by my role.
- As a person, I want to see my contribution history.
~~- As a person, I can add and remove the skills on my skill profile.~~
- As a member, I want to see all the tasks of any type (process, simple for now - extra later) I am working on.

**Simple tasks**

- As a member of a project, I want to create new simple tasks.
- As a member, I can edit any simple task that I have created.
- As a member, I can delete any simple task that I have created, if work has not been done on it.
- As a member, I can record my work on a simple task and mark it complete.

**Processes**

- As a member of a project, I want to plan a process from scratch.
- As a member of a project, I want to be able to edit details of the process.
- As a member of a project, I want to be able to delete a process that has no actual events recorded on it.
- As a member of a project, I want to be able to add requirements of any type in the planned process.
- As a member of a project, I can edit a non-work requirement in the planned process.
- As a member of a project, I can delete a non-work requirement of any type in the planned process, if there are no actual events logged against it.
- As a coordinator of a project, I can edit a work requirement in the planned process.
- As a coordinator of a project, I can delete a work requirement of any type in the planned process, if there are no actual events logged against it.
- As a member of a project, I can commit to working on a process task.
- As a member of a project, I can remove my commitment to work on a process task.
- As a member of a project, I can record my work on a planned process task.
- As a member of a project, I can record my work for a process without a planned process task.
- As a member of a project, I can edit my recorded work on a process.
- As a member of a project, I can delete my recorded work on a process.
- As a member of a project, I can join a process task that someone else already committed to, notifying the other person.
- As a member of a project, I can record non-work inputs and outputs (materials, equipment usage, citations, output produced) that have been planned.
- As a member of a project, I can record non-work inputs and outputs (materials, equipment usage, citations, output produced) that have not been planned.
- As a member of a project, I can delete non-work inputs and outputs (materials, equipment usage, citations, output produced) that I have created.
- As a member of a project, I can see previous and next processes to the one I am working on, so that I can understand the needs for my outputs and the status of my inputs in the sequence of processes.
- As a member of a project, I can mark a process finished.
- As a member of a project, I can mark a finished process as unfinished.

What do you think?

**Comment by fosterlynn** [comment]
I like it, if you think you can do it ! :smile:  Makes sense about helping people grok the model up front using the UI.  Also makes sense to take out the skills profile for this epic.  And it is now down to basically daily work, which makes the most sense for mobile.

We can see if we need to add in any "work order" stuff, but let's not do it now.  I think you had some of that in your visuals too. But in any case, it becomes most useful when you use recipes.

**Comment by bhaugen** [comment]
By the way
> As a member of a project, I can see previous and next processes to the one I am working on, so that I can understand the needs for my outputs and the status of my inputs in the sequence of processes.

We got code that can tell you if your process has neighbors (previous or next), despite not having direct connections.

**Comment by ivanminutillo** [comment]
if you all agree we can close this issue and tranform this list into an epic and user stories :-)
